---
- name: Check if Meraki is installed
  stat:
    path: /usr/local/sbin/m_agent
  register: stat_meraki

- name: Decrypt YBMerakiInstaller
  copy:
    src: files/YBMerakiInstaller.pkg
    dest: /private/tmp/YBMerakiInstaller.pkg
  when: stat_meraki.stat.exists == False

- name: Install YBMerakiInstaller
  command: 'sudo installer -pkg /private/tmp/YBMerakiInstaller.pkg -target /'
  when: stat_meraki.stat.exists == False

- name: Remove YBMerakiInstaller from computer
  file:
    path: /private/tmp/YBMerakiInstaller.pkg
    state: absent
  when: stat_meraki.stat.exists == False
